### ISSUE TITLE
Disable all cache

### ISSUE THREAD

**Issue by rafaelstz** [fballiano/docker-magento2#5]
To development mode, how we can disable all cache? Is good add into README.
Thanks

**Comment by danipolo** [comment]
Which part? REDIS? Varnish? Please, detail little bit more your environment.

**Comment by rafaelstz** [comment]
All cache (Redis, Varnish and OPCache), to no disturb the local development.

**Comment by danipolo** [comment]
Hope this help:

**REDIS**: Just don't configure the env.php to use it.
**Varnish**: You can do it inside the Magento 2 panel, enable the Full Page built-in cache.

You can disable the containers and attack directly to the apache ip or name.

**Comment by rafaelstz** [comment]
@danipolo thanks, this customization below worked to me in the **docker-compose.yml**.

```
version: '2'
services:
  cron:
    image: fballiano/magento2-cron
    depends_on:
      - apache
      # - varnish
    links:
      - db
      - cache
      - clusterdata
      - apache
      # - varnish
    volumes:
      - /var/www/html:/var/www/html
      # - ./varnish.secret:/varnish.secret

  # ssl:
  #   image: fballiano/nginx-ssl-for-magento2
  #   depends_on:
  #     - varnish
  #   links:
  #     - varnish
  #   ports:
  #     - "443:443"

  # varnish:
  #   image: fballiano/varnish
  #   ports:
  #     - "80:80"
  #     - "6082:6082"
  #   depends_on:
  #     - apache
  #   links:
  #     - apache
  #   volumes:
  #     - ./varnish.vcl:/etc/varnish/default.vcl
  #     - ./varnish.secret:/etc/varnish/secret
  #   environment:
  #     - CACHE_SIZE=256M

  apache:
    image: fballiano/magento2-apache-php
    ports:
        - "80:80"
    depends_on:
      - db
      - cache
      - clusterdata
    links:
      - db
      - cache
      - clusterdata
    volumes:
      - /var/www/html:/var/www/html

  db:
    image: mariadb
    ports:
      - "3306:3306"
    volumes_from:
      - dbdata
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2

  dbdata:
    image: tianon/true
    volumes:
      - /var/lib/mysql

  cache:
    image: fballiano/redis-volatile

  clusterdata:
    image: fballiano/redis-volatile
```
